# -*- coding: utf-8 -*-
# vim: ft=yaml
---
# General overrides used across formulas in the org
{%- set LLL = 'Layout/LineLength' %}
{{ LLL }}:
  {%- set rbcp_LLL = rubocop.Cops.get(LLL) %}
  {%- if rbcp_LLL.Max == rbcp_LLL.Bugbear %}
  # Increase from default of `{{ rbcp_LLL.Default }}`
  # Based on https://github.com/PyCQA/flake8-bugbear#opinionated-warnings (`B950`)
  {%- endif %}
  Max: {{ rbcp_LLL.Max }}
{%- set MBL = 'Metrics/BlockLength' %}
{{ MBL }}:
  {%- set rbcp_MBL = rubocop.Cops.get(MBL) %}
  IgnoredMethods:
    {%- for method in rbcp_MBL.IgnoredMethods %}
    - {{ method }}
    {%- endfor %}
  # Increase from default of `{{ rbcp_MBL.Default }}`
  Max: {{ rbcp_MBL.Max }}
{%- set SYL = 'Security/YAMLLoad' %}
{{ SYL }}:
  {%- set rbcp_SYL = rubocop.Cops.get(SYL) %}
  Exclude:
    {%- for path in rbcp_SYL.Exclude %}
    - {{ path }}
    {%- endfor %}

# General settings across all cops in this formula
AllCops:
  NewCops: enable
  {#- This is purposefully simplistic for the time being,
      until (if ever) more advanced configuration is necessary #}
  {%- if rubocop.AllCops.get('Exclude', []) %}
  # Files to ignore completely
  Exclude:
    {%- for path in rubocop.AllCops.Exclude %}
    - {{ path }}
    {%- endfor %}
  {%- endif %}

# Any offenses that should be fixed, e.g. collected via. `rubocop --auto-gen-config`
{%- for cop, config in rubocop.Cops.items() if cop not in [LLL, MBL, SYL] %}
{{ cop }}:
  {#- This is purposefully simplistic for the time being,
      until (if ever) more advanced configuration is necessary #}
  {%- if config.get('Exclude', []) %}
  Exclude:
    {%- for path in config.Exclude %}
    - {{ path }}
    {%- endfor %}
  {%- endif %}
  {%- for k, v in config.items() if k not in ['Exclude'] %}
  {{ k }}: {{ v }}
  {%- endfor %}
{%- endfor %}
