# frozen_string_literal: true

source ENV.fetch('PROXY_RUBYGEMSORG', 'https://rubygems.org')

# Install the `inspec` gem using `git` because versions after `4.22.22`
# suppress diff output; this version fixes this for our uses.
# rubocop:disable Layout/LineLength
gem 'inspec', git: 'https://gitlab.com/saltstack-formulas/infrastructure/inspec', branch: 'ssf'
# rubocop:enable Layout/LineLength

# Install the `kitchen-docker` gem using `git` in order to gain a performance
# improvement: avoid package installations which are already covered by the
# `salt-image-builder` (i.e. the pre-salted images that we're using)
# rubocop:disable Layout/LineLength
gem 'kitchen-docker', git: 'https://gitlab.com/saltstack-formulas/infrastructure/kitchen-docker', branch: 'ssf'
# rubocop:enable Layout/LineLength

gem 'kitchen-inspec', '>= 2.5.0'
gem 'kitchen-salt', '>= 0.7.2'
{%- if semrel_formula in [
      'apache',
      'consul',
      'dnsmasq',
      'golang',
      'nfs',
      'nginx',
      'node',
      'openssh',
      'openvpn',
      'packages',
      'php',
      'postgres',
      'salt',
      'snmp',
      'vault',
    ] %}
{%-   if semrel_formula in ['openvpn'] %}
gem 'rspec-retry'
{%-   endif %}

group :vagrant do
  gem 'kitchen-vagrant'
end
{%-   if semrel_formula in ['vault'] %}

# v7 needed for compatibility with OpenSSL v3
gem 'net-ssh', '~> 7'
{%-   endif %}
{%- endif %}
